# Project Information
site_name: PagerDuty Best Practices for On-Call Teams Ops Guide
site_description: This guide is a collection of resources from PagerDuty and others that is intended to help teams new to being on-call navigate the ins and outs of response.
site_author: PagerDuty, Inc.
site_favicon: 'assets/img/favicon.png'
site_url: https://goingoncall.pagerduty.com

# Repository
repo_url: https://github.com/PagerDuty/goingoncall-docs

# Copyright
copyright: 'Copyright &copy; PagerDuty, Inc.'

# Theme
theme: 'material'
theme_dir: 'theme'
extra_css: ['assets/css/pagerduty.css','assets/css/custom.css']
extra_javascript: ['js/github_forks.js']
extra:
  favicon: 'assets/img/favicon.png'
  logo: 'assets/img/icon.png'
  cover: 'assets/img/covers/default.png'
  palette:
    primary: 'green'
    accent: 'blue grey'
  author:
    github: 'PagerDuty'
    twitter: 'PagerDuty'

# Dev URL
dev_addr: '0.0.0.0:8080'

# Contents
pages:
  - Home: 'index.md'
  - Introduction: 'intro.md'
  - Technical Preparations: 'tech.md'
  - Setting Team Norms: 'people.md'
  - Building On-Call Culture: 'culture.md'
  - Recommendations for Managers: 'managers.md'
  - Implementation Suggestions: 'implementation.md'
  - Next Steps: 'next_steps.md'
  - Additional Resources: 'resources.md'


# Analytics
google_analytics: ['UA-8759953-1', 'auto']

# Extensions
markdown_extensions:
  - toc:
      permalink: '#'
  - sane_lists:
  - admonition:
  - meta:
  - pymdownx.details:
  - pymdownx.extra:
  - pymdownx.mark:
  - pymdownx.tilde:
