# Project Information
site_name: PagerDuty Best Practices for On Call Teams Ops Guide
site_description: This guide is a collection of resources from PagerDuty and others that is intended to help teams new to being on-call navigate the ins and outs of response.
site_author: PagerDuty, Inc.
site_url: https://goingoncall.pagerduty.com/

# Repository
repo_url: https://github.com/PagerDuty/goingoncall-docs

# Copyright
copyright: 'Copyright &copy; PagerDuty, Inc.'

# Theme
theme:
  name: pagerduty
  title: 'Best Practices for On Call Teams'

# Contents
nav:
  - Home: 'index.md'
  - Introduction: 'intro.md'
  - Technical Preparations: 'tech.md'
  - Setting Team Norms: 'people.md'
  - Building On-Call Culture: 'culture.md'
  - Recommendations for Managers: 'managers.md'
  - Implementation Suggestions: 'implementation.md'
  - Next Steps: 'next_steps.md'
  - Additional Resources: 'resources.md'

# Analytics
google_analytics: ['UA-8759953-1', 'auto']

# Extensions
markdown_extensions:
  - toc:
      permalink: '#'
  - sane_lists:
  - admonition:
  - meta:
  - pymdownx.details:
  - pymdownx.extra:
  - pymdownx.mark:
  - pymdownx.tilde:
  - pymdownx.highlight:
  - pymdownx.superfences:
  - pymdownx.tabbed:

# Development URL, bind to local only.
dev_addr: '127.0.0.1:8000'
